[windows-terminal]
source = "WindowsTerminal"
target = "~/appdata/local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState"
type = "symlink"

[wezterm]
source = "wezterm"
target = "~/.config/wezterm"
type = "symlink"

 
[powershell]
source = "Powershell/Microsoft.PowerShell_profile.ps1"
target = "~/Documents/PowerShell/Microsoft.PowerShell_profile.ps1" 
type = "hardlink"

[nushell]
source = "nushell"
target = "~/AppData/Roaming/nushell"
type = "symlink"

[starship]
source = "starship/starship.toml"
target = "~/.config/starship.toml" 
type = "hardlink"

[zoxide]
source = "zoxide/zoxide.nu"
target = "~/.zoxide.nu"
type = "hardlink"

[bat]
source = "bat"
target = "~/AppData/Roaming/bat"
type = "symlink"

[neovim]
source = "nvim"
target = "~/appdata/local/nvim"
type = "symlink"

[zed]
source = "zed"
target = "~/appdata/roaming/Zed"
type = "symlink"

[glaze-wm-2]
source = "glaze-wm-2"
target = "~/.glaze-wm" 
type = "symlink"

[glaze-wm-3]
source = "glaze-wm-3"
target = "~/.glzr/glazewm" 
type = "symlink"

[zebar]
source = "zebar"
target = "~/.glzr/zebar" 
type = "symlink"

