[neovim]
source = "nvim"
target = "~/appdata/local/nvim"
type = "symlink"

[windows-terminal]
source = "WindowsTerminal"
target = "~/appdata/local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState"
type = "symlink"

[starship]
source = "starship/starship.toml"
target = "~/.config/starship.toml" 
type = "hardlink"
 
[powershell]
source = "Powershell/Microsoft.PowerShell_profile.ps1"
target = "~/Documents/PowerShell/Microsoft.PowerShell_profile.ps1" 
type = "hardlink"

[glaze-wm]
source = "glaze-wm"
target = "~/.glaze-wm" 
type = "symlink"

[wezterm]
source = "wezterm/wezterm.lua"
target = "~/.wezterm.lua"  
type = "hardlink"

[nushell]
source = "nushell"
target = "~/AppData/Roaming/nushell"
type = "symlink"

[zoxide]
source = "zoxide/zoxide.nu"
target = "~/.zoxide.nu"
type = "hardlink"

[bat]
source = "bat"
target = "~/AppData/Roaming/bat"
type = "symlink"
